# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - appemprestimo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v17.13.9

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: Verificar arquivos
        run: dir Caravana


      - name: Restore NuGet packages
        run: nuget restore Caravana/Caravana.sln

      - name: Publish to folder
        run: msbuild Caravana/Caravana.sln /t:Publish /p:Configuration=Release;PublishDir="PublishOutput"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: published/**

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1075B10768A546A2899A98FD1BE5199C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_286184503347429793FFC9F3444B76FD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0E2F50659DA142BCBED546638ABBEBD6 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appemprestimo'
          slot-name: 'Production'
          package: .

          














